### ISSUE TITLE
Security issues?

### ISSUE THREAD

**Issue by Anon-2018** [TelegramMessenger/MTProxy#184]
Hey folks,

would like to get comments on: https://yvoinov.blogspot.com/2018/06/mtproto-proxy.html

It seems MTProxy is doing requests to https://dns.google.com with clients originating ip address which can be seen on ISP level if transparent proxy used.

**Comment by stek29** [comment]
I've written a long comment with detailed explanations, but it's gone due to connection issues, so I'll just write a TLDR on why that post is bullshit.

- Telegram apps use domain fronting for those requests, so SNI based DPI would only see google.com
- SNI is mandatory in TLS 1.3, but it's also encrypted in TLS 1.3
- Telegram is definitely not the only app which uses DNS.google.com
- If attacker can mitm on google.com, you're definitely fucked up beyond event horizon.

So, author clearly hasn't even tried to do some research.
