### ISSUE TITLE
Proxy sponsors has been hide on unofficial telegram by their admins

### ISSUE THREAD

**Issue by james12974** [TelegramMessenger/MTProxy#330]
Hello
I have to report something that is really no less important than blocking proxies 
Recently most of unofficial telegram applications such as rahagram and igram and vidogram they take action to hide mtproxies sponsors and for users that are using telegram under their app cant see the proxy sponsor and for this we are just paid money for servers and they have not any efficiency for our channels.
I think this is better telegram put a section for proxies and we'll determine what telegram packages can be connected to our proxies.
If telegram doesnt do anything then we can no longer continue building the proxy so we want you to be serious with this .

**Comment by kooran** [comment]
@james12974 Thank you for your note! i approve this issue as well as it is "no less important than proxies getting blocked" we proxy providers tried everything we could to stop this issue by ourselves , but no help, we even tried to give people motivation to use only and only the original telegram, but still no help and every day it's getting worse and we're almost close to giving it up because we can't afford providing more servers without sponsored channel and that will cause a large drop of telegram users!! THIS IS AN URGENT ISSUE!!!

**Comment by IvanIvanov3432** [comment]
THIS IS AN URGENT ISSUE!!!

**Comment by MasterGroosha** [comment]
This is not related to MTProxy repository at all. Please consider closing your issue.

**Comment by WebShark025** [comment]
@stek29 I don't undrestand the reason behing closing this issue. This is completely related to both Telegram and MTProxy developers, because there should be a way to identify the official Telegram application packets from the unofficial ones, and to filter them out.
Please consider this as an urgent issue as it's causing lots and lots of losses to us, the proxy creators.

**Comment by MasterGroosha** [comment]
@WebShark025 

> there should be a way to identify the official Telegram application packets from the unofficial ones, and to filter them out

How does it relate to you, "the proxy creator"?
Hiding "proxy sponsor" channel is client-side feature.

**Comment by WebShark025** [comment]
> @WebShark025
> 
> > there should be a way to identify the official Telegram application packets from the unofficial ones, and to filter them out
> 
> How does it relate to you, "the proxy creator"?
> Hiding "proxy sponsor" channel is client-side feature.

Your reply is a little bit unclear;

What I meant from 'the proxy creator' was 'the person/group who pays for the servers, runs the proxy script and shares it with everyone'.

What I asked from @stek29 and other 'developers of the MTProxy' (ALSO INCLUDING the developers of Telegram) was: there should be a way to find which application the clients are using, is it the official Telegram or no. And this feature should be implemented both on the client side (to send, for example, the API ID to the proxy server) and on the server side (the proxy script I mean, to recognize the packets).

P.S: I know the client-side should be done by the Telegram team, but why I started this issue here is:
1. because if this issue/feature is proposed by the developers of MTProxy script to the Telegram team, it would be way more attended by their staff 
2.  this team also needs to implement the handling of this feature on the server-side script.

**Comment by kooran** [comment]
This issue still stands! And it's a big issue for MTProto developers......
We pay for servers, they use for free and take money of their sponsers while our sponsers are unhappy...

**Comment by megagpu** [comment]
Yeah but I don't want to see any Telegram channel with porn and sexy pics and videos posted in it on my mom's account!! Cause she'll blame me for it!

**Comment by megagpu** [comment]
I don't mean EVERY Telegram proxy sponsor is a +18 channel tho... I'm saying it cuz I'm seeing so many of 'em lately on top... <3

**Comment by WebShark025** [comment]
> I don't mean EVERY Telegram proxy sponsor is a +18 channel tho... I'm saying it cuz I'm seeing so many of 'em lately on top... <3

I mean your mom can report the channel tho...
And also, At least in Iran, there haven't been that many +18 channels on the proxies, because most of the proxy owners are those who are in this job for a long time, and they don't want any sketchy content being promoted on their proxies. It will reduce the number of people connected to their proxies significantly and it's not a viable thing to do.

**Comment by peacemaker907** [comment]
Well, i downloaded an app.. It asked for permissions..found out, it wasn't a signed app. It opened telegram and tried to get me to join telegram server... I cleared it, and then IMMEDIATELY STARTED receiving messages in telegram about antivirus protection..several a day. 
Then, my calendar on android..the local side, not my Google calendar was bombarded with scheduled entries.. Around a dozen every single day..fix your phone, your antivirus software is out of date, reminder to fix your antivirus... It goes off day and night.. I cleared my calendar storage and calendar app and calendar sync data but i cannot get rid of the proxy sponsor on telegram..please advise:

**Comment by Zafaryyy** [comment]
How.i make proxy sponsor

**Comment by Zafaryyy** [comment]
How.i make proxy sponsor

**Comment by Zafaryyy** [comment]
If anyone help me then I pay you extra gift also
