### ISSUE TITLE
Is it safe to use any mtproto proxy server?

### ISSUE THREAD

**Issue by VahidPY** [TelegramMessenger/MTProxy#68]
Hi everyone,
I just want to be sure, is it safe to use any mtproto proxy server? As I know telegram apps encrypt all the messages between client and telegram server, does it matter who the proxy server owner is? I've been asked this question a lot and I believe it is not important because if it was, everyone else would read the messages on the network such as governments, so telegram doesn't trust the proxy servers too.

**Comment by p1ratrulezzz** [comment]
Yes, its safe. The proxy server only knows your ip address. All the traffic between proxy server and your client is encrypted using aes256 cipher and as I was able to understand it also uses secret key of proxy to encrypt the messages that are actually already encrypted by telegram client itself and obfuscates the traffic in order to hide it from provider and they could not analyze packets to say if it is a http traffic or telegram. And then proxy sends this encrypted packets to telegram server itself. In many of these proxy implementations it is clear how encryption works so you can read it in the source.

**Comment by FreedomPrevails** [comment]
@VahidPY 100% safe. the proxy can only know about client IP address. nothing else.

**Comment by onehamed01** [comment]
But I think that this is not True to Say that "yes this stack is safe".

**Comment by Drjacky** [comment]
@p1ratrulezzz 
> All the traffic between proxy server and your client is encrypted using aes256 cipher 

So, how can the other machine/device of us show the pure text?

**Comment by onehamed01** [comment]
i dont have any project of telegram proxy
